[build]
builder = "NIXPACKS"
watchPatterns = ["demo/**"]

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20"]

[build.nixpacksPlan.phases.install]
cmds = ["cd demo && npm ci"]

[build.nixpacksPlan.phases.build]
cmds = ["cd demo && npm run build"]

[deploy]
startCommand = "cd demo && npm run start"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
